# Generated by Django 4.2.3 on 2023-08-06 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_book_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('format', models.CharField(max_length=3)),
                ('weight', models.PositiveIntegerField()),
                ('number_of_sheets', models.PositiveIntegerField()),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='papers_cover/')),
                ('price', models.PositiveIntegerField()),
            ],
        ),
    ]
