# Generated by Django 4.2.3 on 2023-08-09 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_cart_book_quantity_gifts_quantity_hobbyart_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='product_model',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
