# Generated by Django 4.2.3 on 2023-08-10 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_cartitem_product_model'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gifts',
            old_name='name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='hobbyart',
            old_name='name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='officesupplies',
            old_name='name',
            new_name='title',
        ),
    ]
