# Generated by Django 4.2.3 on 2023-08-11 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_order_created_at_order_order_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='paper',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
