# Generated by Django 4.2.3 on 2023-08-05 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='appuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
