# Generated by Django 4.2.3 on 2023-08-11 17:12

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('auth_web', '0002_appuser_first_name_appuser_last_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffGroup',
            fields=[
            ],
            options={
                'verbose_name': 'Staff Group',
                'verbose_name_plural': 'Staff Groups',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.group',),
            managers=[
                ('objects', django.contrib.auth.models.GroupManager()),
            ],
        ),
    ]
